name: Validate Markdown

on:
  push:
    paths:
      - "**.md"
      - "**.markdown"
  pull_request:
    paths:
      - "**.md"
      - "**.markdown"

jobs:
  validate:
    name: Validate Markdown Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint '**/*.md' --ignore node_modules

      # Optional - Add more tools if needed
      - name: Check links in Markdown files
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: ".github/markdown-link-check-config.json"
          folder-path: "."
          file-extension: ".md"
