name: Build and Deploy Quartz Site

on:
  push:
    branches:
      - main # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for correct git history
          token: ${{ github.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Clone Quartz
        run: |
          git clone https://github.com/jackyzha0/quartz.git temp_quartz

      - name: Setup and Configure Quartz
        run: |
          cd temp_quartz
          npm install

          # Copy your content files to the Quartz content directory
          mkdir -p content
          cp -r ../* content/ 2>/dev/null || true
          # Avoid copying temp_quartz folder into itself
          rm -rf content/temp_quartz

      - name: Build Quartz Site
        run: |
          cd temp_quartz
          npx quartz build

      - name: Commit HTML to Repository
        run: |
          # Create docs directory if it doesn't exist
          mkdir -p docs

          # Copy the generated files
          cp -r temp_quartz/public/* docs/

          # Configure git
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

          # Stage, commit, and push the changes
          git add docs/
          git commit -m "Add generated HTML files [skip ci]" || echo "No changes to commit"
          git push
