name: Build and Deploy Quartz Site

on:
  push:
    branches:
      - main # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for correct git history
          path: content # Check out your content into a subdirectory

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Clone Quartz
        run: |
          git clone https://github.com/jackyzha0/quartz.git

      - name: Setup and Configure Quartz
        run: |
          cd quartz
          npm install

          # Copy your content to the Quartz content directory
          rm -rf content
          cp -r ../content/* .
          cp -r ../content/.* . 2>/dev/null || true

      - name: Build Quartz Site
        run: |
          cd quartz
          npx quartz build

      - name: Commit HTML to Repository
        run: |
          # Move the generated files to a docs directory in the repository root
          mkdir -p ../content/docs
          cp -r quartz/public/* ../content/docs/

          # Go to the content repository directory
          cd ../content

          # Configure git
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

          # Add and commit the changes
          git add docs/
          git commit -m "Add generated HTML files [skip ci]" || echo "No changes to commit"

          # Push to the repository
          git push https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
